name: Attach bin to release

on:
  push:

jobs:
  build-mev-geth-bin:
    runs-on: ubuntu-latest
    container: 
        image: debian:buster
        env: 
          DEBIAN_FRONTEND: noninteractive
          
    name: Build and upload mev-geth to release assets
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      
      - name: Install make
        run: apt update; apt-get install -yq build-essential zip ca-certificates
      
      - name: build blockbook
        run: make blockbook